# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 61af9a56b2f606fdb5f6c2f8190101f6f9ead73b20c461b91686109e51db0eae160e59e3af50c6d27ed74e1dcd4ab5210c3c96d8c366e0a619b56c58548ec731

test:
  secret_key_base: 1e1220e808cf4f5964a45fa4e1b5daafc7ec4614fbae54f47e220691230f6febcef7f267a3944fc9b7d69ea857a908554dd0ba6b9f64cb67b9cc53fb61ccd847

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
